version: '3.7'
services:
  app:
    container_name: ${APP_NAME}-app
    build: ./docker
    ports:
      - "8100:8100"
    command: ["/usr/local/bin/ionic", "serve", "--no-open", "--external"]
    volumes:
      - .:/app